name: task2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_otp_text_field: ^1.5.1+1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_image/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/splash_image/app_icon.png"
flutter:
  uses-material-design: true
  assets :
    - assets/images/
    - assets/splash_image/
    - assets/jsonlangs/
